version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: tx-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d txdemo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
